### ISSUE TITLE
ore through portals: Big Bug

### ISSUE THREAD

**Issue by ElweThor** [blaxxun-boop/Backpacks#1]
As in the subject, I "got aware" of that bug while I wasn't searching for it: I had to craft some wards (WardIsLove mod) and it was requiring a forge, so 6 copper ingots: I simply placed such ingots in my Backpack, to move (walking) in a different place, in my base then, forgetting I had them, I teleported to another base requiring a ward too. Once I've been there, I opened the Backpack, crafted the forge... then... o___O!!! I realized I teleported the ingots to there! =:O

P.S.
nice job, with the Backpack, by using it like having a chest into inventory. 👍

**Comment by blaxxun-boop** [comment]
That's not a bug, the mod is just super basic right now. There will be more to it later on.
