### ISSUE TITLE
Can't open Backpack

### ISSUE THREAD

**Issue by BlackDogTM** [blaxxun-boop/Backpacks#13]
hey, is it usual that I can't open the backpack?

**Comment by blaxxun-boop** [comment]
You can open backpacks by hovering them in your inventory and pressing interact. It should also state that in their tooltip. If it doesn't, you probably have a mod that prevents this, e.g. Valheim Plus.

**Comment by BlackDogTM** [comment]
ah thanks, 

the bug was me being too lazy to read lol

/ closed
