### ISSUE TITLE
When using AzuExtendedInventory the bags block bottom rows

### ISSUE THREAD

**Issue by emxia** [blaxxun-boop/Backpacks#16]
Could we make it so the backpack window can be moved and the position saved where you move it to?

**Comment by blaxxun-boop** [comment]
Free your mouse, hold CTRL, drag and drop the window.

**Comment by emxia** [comment]
blaxxun,
did you push a change for this, or is it already implemented? It does not function for me if the ladder

**Comment by blaxxun-boop** [comment]
It's a feature of AzuExtendedInventory. If it doesn't work for you, ask Azu about it.
