### ISSUE TITLE
Build your own backpack can't have spaces in the name for the backpack.

### ISSUE THREAD

**Issue by AgentX2006** [blaxxun-boop/Backpacks#17]
You can't have a space in the name for the backpack.

Works: Blaxxunpack: # Give your backpack an amazing name!
Does not work: Blaxxun's Pack: # Give your backpack an amazing name!

**Comment by blaxxun-boop** [comment]
Spaces are perfectly fine. the apostrophe is not. If you want an apostrophe is your name, quote it:
`"Blaxxun's Pack": # Give your backpack an amazing name!`

You pretty much have to do that for all special characters.

**Comment by AgentX2006** [comment]
Tried quoting it and that didn't work. Works fine with the apostrophe as long as there are no spaces.
