### ISSUE TITLE
How to open backpack to put items inside?

### ISSUE THREAD

**Issue by woodstockfurygit** [blaxxun-boop/Backpacks#20]
I have the mod installed and created a backpack. However, I can't seem to figure out how to open it... Any help would be greatly appreciated. Thank you!!

**Comment by blaxxun-boop** [comment]
You hover it and press your interact key. Make sure you aren't using Equipment and Quick Slots, which breaks pretty much all other mods that touch the inventory, including backpacks. It's the worst implementation of that feature. Use any of the alternatives instead, they work waaay better.
E.g. https://valheim.thunderstore.io/package/Azumatt/AzuExtendedPlayerInventory/
Just make sure to dump all your stuff into a chest, before you make the switch.
