### ISSUE TITLE
Default Naked Male Character on Start Screen

### ISSUE THREAD

**Issue by adbeagley** [blaxxun-boop/Backpacks#21]
I'm using the BowsBeforeHoes mod along with AzuExtendedPlayerInventory and I'm able to upgrade and use the quivers just fine but after quitting the game and restarting it, if the character has a quiver in their inventory (whether the quiver is equipped or not) the character appears as the default bald male character. Logging in and connecting to a world still works and all of the characters equipment is still there along with the quiver at least. So it's mostly just disconcerting.

**Comment by blaxxun-boop** [comment]
Fixed in v1.2.5
