### ISSUE TITLE
hello! Smoothbrain~ Warning:ManagerDetector...

### ISSUE THREAD

**Issue by krintiz** [blaxxun-boop/Backpacks#22]
[Warning:ManagerDetector] Checking for managers.

[Debug  :ManagerDetector] The following mods have ItemManager:
[Debug  :ManagerDetector] Backpacks [org.bepinex.plugins.backpacks 1.2.4]
[Debug  :ManagerDetector] The following mods have ItemDataManager:
[Debug  :ManagerDetector] Backpacks [org.bepinex.plugins.backpacks 1.2.4]
2023.08.27 

I love your mod.
I got this message, can I use it?
(I am not good at English.)

**Comment by krintiz** [comment]
When I use this mod, I'm taking off all my gear where I choose my character. And an error occurs after a while. Please check.

**Comment by blaxxun-boop** [comment]
Fixed in v1.2.5
