### ISSUE TITLE
[Compatibility Issue] AzuCraftyBoxes

### ISSUE THREAD

**Issue by ryanburst** [blaxxun-boop/Backpacks#34]
When using this backpack mod, the contents of the backpack are not included in available materials for crafting through the [AzuCraftyBoxes](https://thunderstore.io/c/valheim/p/Azumatt/AzuCraftyBoxes/) mod. I'm opening a ticket with both as I'm not sure which might need to be updated.

I think an adjustment needs to be made to this one, similar to what [Adventure Backpacks](https://thunderstore.io/c/valheim/p/Vapok/AdventureBackpacks/) by Vapok did with [their mod](https://thunderstore.io/c/valheim/p/Azumatt/AzuCraftyBoxes/).

**Comment by blaxxun-boop** [comment]
Nope, support for this would have to be added in AzuCraftyBoxes.
