### ISSUE TITLE
[CRITICAL BUG] Copy items using a backpack.

### ISSUE THREAD

**Issue by Tungermax** [blaxxun-boop/Backpacks#36]
We copy objects using a backpack.
There is a way to get additional loot using a backpack.
Algorithm
-Place items in the backpack
-Throw out all the items on the ground
-Restart the game (the things that were in the backpack have not gone anywhere) Everything that you threw away will be on the floor.
-Pick up all the objects from the ground.
Congratulations, you have doubled your items.

**Comment by blaxxun-boop** [comment]
This is how to duplicate items in vanilla, yes.
