### ISSUE TITLE
Upgrading backpacks has no effect

### ISSUE THREAD

**Issue by PrincessRTFM** [blaxxun-boop/Backpacks#40]
I'm in a singleplayer world, having edited my config files outside of the game before launching. I've uploaded my 
[`org.bepinex.plugins.backpacks.cfg`](https://github.com/user-attachments/files/15749423/org.bepinex.plugins.backpacks.txt) and my [`BackpacksJamesJonesJiuJitsu.yml`](https://github.com/user-attachments/files/15749425/BackpacksJamesJonesJiuJitsu.txt) files, although I had to change the extensions to `txt` for github to recognise them. My [`LogOutput.log`](https://github.com/user-attachments/files/15749420/LogOutput.log) is also available, as I saw the previous issue on this subject was closed for not providing it.

Summary: I can craft backpacks easily enough and without issue, but when I upgrade a backpack, nothing happens at all. I've tried crafting a brand new backpack, upgrading it immediately, and only then opening it; crafting a new backpack, equipping it, reopening my inventory, unequipping it, upgrading it, re-equipping it, and then reopening my inventory; and upgrading a backpack while wearing it. In all cases, I also attempted to put an item into the backpack after upgrading it.

At no point did anything _break_, and no errors were shown, but the backpacks never changed size at all. This includes the explorer's backpack, as well as a variety of the filtered backpacks enabled from the YAML file.

**Comment by blaxxun-boop** [comment]
[Info   :   BepInEx] Loading [Equipment and Quick Slots 2.1.13]

Remove this mod. It's crap. You already have AzuExtendedPlayerInventory installed, which has the same features, but doesn't break every other mod that interacts with the inventory. You might have to enable the equipment slots in the mods config, because you had both installed. Or just reset the config for AzuExtendedPlayerInventory, after removing the other mod.

Should be fine then.

**Comment by PrincessRTFM** [comment]
That was indeed exactly the problem! I had no idea EQS was such an issue.

**Comment by blaxxun-boop** [comment]
General rule of thumb: Avoid any mod that has Randys name on it. You will spend way less time on troubleshooting and have more time to actually play the game.
