### ISSUE TITLE
Multiple status effects

### ISSUE THREAD

**Issue by Lief08** [blaxxun-boop/Backpacks#42]
I have been attempting to get multiple status effects to work on a pack but it doesn't seem to function. I manage to get something like SlowFall or SetEffect_WolfArmor but if I try to append both, neither work. I have tried this comma delimited (with and without space) as well as simple space delimited. 

I'm not clear if it is intended, a bug or I'm doing something obviously wrong.

**Comment by blaxxun-boop** [comment]
Items in Valheim can only have one status effect by default. If you want to have two, you would have to combine them via WackysDB and then use that one.
