### ISSUE TITLE
Backpacks translations

### ISSUE THREAD

**Issue by Turbero** [blaxxun-boop/Backpacks#43]
Hello.

I was wondering how to translate the Backpacks mod, because I saw a English.yml file but couldn't find it once I download and install the mod in my profile.

I also try adding a Spanish.yml file inside the plugin mod folder but didn't work out.

Is there any way to translate the messages of the English.yml file? 

Thanks in advance! Great work!

**Comment by blaxxun-boop** [comment]
Add a Backpacks.Spanish.yml to your config folder and add the translations from the English.yml to that.

**Comment by Turbero** [comment]
Oh ok I will rename the file and give it another go in the evening and let you know. Thanks for the quick reply!
