### ISSUE TITLE
Backpack lost after recovering gravestone

### ISSUE THREAD

**Issue by MachinusRhapsody** [blaxxun-boop/Backpacks#44]
First off, absolutely incredible mods! The mods you create are some of the absolute best to fit the look and feel of Valheim, and the sheer number of excellent features you have created is staggering!

Most of my server's players have died and recovered their items without issue. One player who recovered his gravestone last night has had his backpack go missing. I saw it was on his gravestone before he recovered it, but it was not moved back into his inventory when he looted his grave. I'm using the server setting which only allows one backpack per player, so he is unable to craft an additional backpack.

Is there a specific log I can provide to help figure out what happened? I'm not sure how the record that the player has created their allocated backpack is stored, is there a way for players to recover a lost backpack or for a server admin to remove any existing record of the per-player backpack?

**Comment by blaxxun-boop** [comment]
Sounds like you are using a mod that adds equipment slots and the backpack went into one of the invisible slots in the inventory. Just die again to fix this.
