### ISSUE TITLE
Failed to draw this field, check log for details

### ISSUE THREAD

**Issue by MrShersh** [blaxxun-boop/Backpacks#52]
Hey, **mate**!

**First of all: Love your work <3**

I use mod "SmoothBrains Backpacks" and when I go to Backpacks tab in configurator manager, I get console error spam:

> **[Error  :Configuration Manager] Failed to draw setting Upgrading Costs - System.NullReferenceException: Object reference not set to an instance of an object
>   at ItemManager.Item+<>c__DisplayClass86_0.<drawRequirementsConfigTable>b__0 (BepInEx.Configuration.ConfigEntryBase cfg) [0x00095] in <0566256e63fe4f4bbdea48873a310e6a>:0
>   at ConfigurationManager.SettingFieldDrawer.DrawSettingValue (ConfigurationManager.SettingEntryBase setting) [0x0000e] in C:\Users\poiqwe\source\repos\BepInEx.ConfigurationManager\ConfigurationManager\SettingFieldDrawer.cs:53
>   at ConfigurationManager.Updater.DrawSingleSetting (ConfigurationManager.SettingEntryBase setting) [0x00017] in C:\Users\poiqwe\source\repos\BepInEx.ConfigurationManager\ConfigurationManager\ConfigurationManager.cs:810**

This happen only when Backpack tab is open. Also I see, what three lines in GUI show errors (IMG)

> **Failed to draw this field, check log for details**

**About the mod functionality - it is works good.**

![image](https://github.com/user-attachments/assets/2eeedefa-7de6-4bbb-8df1-5912d2bb7ef8)

**Additional information:**
I use:
License Valheim 0.218.19 (steam pre 27 update, because update from 27 august was broke HD mod)
Latest Bepheinx from thunderstore 5.4.22.0
Enhanced BepInEx Configuration Manager

**Comment by blaxxun-boop** [comment]
Please always share your log file, when reporting any issues, so I don't have to guess.

Not sure what "enhanced bepinex configuration manager" is supposed to be, but a lot of the custom configuration managers are feature stripped, because some people think "no one uses this feature anyway". My mods use _all_ features the configuration manager has to offer, so always just use the official one that hasn't been tampered with.

https://thunderstore.io/c/valheim/p/Azumatt/Official_BepInEx_ConfigurationManager/

**Comment by MrShersh** [comment]
> Please always share your log file, when reporting any issues, so I don't have to guess.
> 
> Not sure what "enhanced bepinex configuration manager" is supposed to be, but a lot of the custom configuration managers are feature stripped, because some people think "no one uses this feature anyway". My mods use _all_ features the configuration manager has to offer, so always just use the official one that hasn't been tampered with.
> 
> https://thunderstore.io/c/valheim/p/Azumatt/Official_BepInEx_ConfigurationManager/

You was right, it is was my fall.

Sorry for not posting the full log file. I thought that just the error lines would be enough. But I realize I was wrong.

I was using the wrong configurator manager. Now I don't have this problem anymore.

Thank you for your reply!

Again: very cool work, I literally fell in love with how it was implemented <3

P.S. Not long ago, I implemented a backpack mod for another game :D :
[https://www.nexusmods.com/newvegas/mods/87761](url)
