### ISSUE TITLE
Custom backpacks dont always appear

### ISSUE THREAD

**Issue by GracefulUni** [blaxxun-boop/Backpacks#53]
I'm having an issue with this mod where I have a few backpack yml files and some of them show up on the crafting bench and some dont.

I went in to the yml file of the ones that i clearly know the recipes for and I edit the file so i can do a save and once I saved all the other backpacks appeared in the forge workbench

I dont know what the cause of this bug is but it would be great if it could be patched please.

I have a feeling having multiple yml files for backpacks it cant read them all for recipes to appear?

**Comment by blaxxun-boop** [comment]
Check your log for errors with the YAML files, make sure to pick up an item, to refresh the list of known recipes, make sure to not be interacting with a crafting station, while adding more recipes.

**Comment by GracefulUni** [comment]
there are no errors in the logs and its always on a new character and grabbing all items needed, i fixed it by removing all groups and adding in only on valid list section and using caps Workbench and Forge instead of workbench, forge etc, never had an issue again after doing new character tests, so prob groups isnt working properly.

Probably needs a look at how groups are being handled but after removing that ive had no issues so idk
